framework: mocha
tier: large
preRun:
     command:
        - npm install
        - npm run react
preMerge:
  pattern:
    - "./packages/enzyme-test-suite/test/*.js"
postMerge:
  pattern: 
    - "./packages/enzyme-test-suite/test/*.js"
postRun:
     command:
        - node --version
configFile: "mocharc.yml"
version: 1.0
