framework: mocha
tier: large
postMerge:
  pattern: 
    - "./packages/enzyme-test-suite/test/*.js"
preMerge:
  pattern:
    - "./packages/enzyme-test-suite/test/*.js"
preRun:
     command:
        - npm install
        - sh install-relevant-react.sh 13
postRun:
     command:
        - node --version
configFile: "mocharc.yml"
version: 1.0
