---
framework: mocha                  # Mention the testing framework mocha or jest
postMerge:
    pattern:
    - "./packages/enzyme-test-suite/test/*.jsx"
    - "./packages/enzyme-test-suite/test/*.js"            # Glob pattern to path where tests that should run post-merge are written
preMerge:
    pattern:
    - "./packages/enzyme-test-suite/test/*.jsx"
    - "./packages/enzyme-test-suite/test/*.js"               # Glob pattern to path where tests that should run pre-merge are written
preRun:
    - npm install                   # Mention pre-run steps here
    - sh install-relevant-react.sh 13
postRun:
    - node --version                # Mention post-run steps here
version: 2.0

